{"name": "test_login_incorrecto", "status": "passed", "description": "Test para verificar que el login falla con credenciales incorrectas", "start": 1753723463707, "stop": 1753723464723, "uuid": "6d5c8edb-7611-4f74-85a8-5bfec83e1763", "historyId": "1a7c0073c4b528c4a9aa616ca651f6c7", "testCaseId": "1a7c0073c4b528c4a9aa616ca651f6c7", "fullName": "Tests.test_login#test_login_incorrecto", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MacBook-Pro-de-emiliano.local"}, {"name": "thread", "value": "59987-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}], "titlePath": ["Tests", "test_login.py"]}